### PR TITLE
fix(tool): keep .otelc-build by default for debugging

### LINKED ISSUE #393: Keep `.otelc-build` by default
Keep .otelc-build by default for debugging purpose

### PR DESCRIPTION
**Pull request by IstvanCsVarga**
## Description

`GoBuild()` no longer removes `.otelc-build/` after the build completes.
Backed-up files (`go.mod`, `go.sum`, etc.) are still restored and generated
runtime files are still removed, but the working directory is preserved so
users can inspect intermediate build artifacts for debugging.

The backup restoration logic is extracted into a `restoreBackups()` helper,
which `Cleanup()` calls internally — no behavior change for `otelc cleanup`.

## Motivation

Keeping `.otelc-build/` after a build makes it easier to debug instrumentation
issues by inspecting matched rules, extracted packages, and the go build cache.
Users can still run `otelc cleanup` to remove it explicitly.

Fixes #393

---

## Checklist

- [x] PR title follows [conventional commits](https://www.conventionalcommits.org/) format
- [x] Code formatted: `make format`
- [x] Linters pass: `make lint`
- [x] Tests pass: `make test`
- [x] Tests added for new functionality
- [x] Tests follow [testing guidelines](docs/testing.md)
- [ ] Documentation updated (if applicable)

### CODE REVIEW

File: tool/internal/setup/cleanup.go [hunk 1]
```diff
@@ -11,10 +11,10 @@ import (
 	"github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/util"
 )
 
-// Cleanup removes all artifacts created by the setup and build phases.
-// It is idempotent and best-effort: individual failures are logged as warnings
-// but do not stop the overall cleanup.
-func Cleanup(ctx context.Context) error {
```
Comment (y1yang0) [inline tool/internal/setup/cleanup.go:17]: Maybe simply `Cleanup(ctx context.Context, cleanAll bool)` & `otelc go build(cleanAll=false)` & `otelc cleanup (cleanAll=true)`?

Comment (IstvanCsVarga) [reply tool/internal/setup/cleanup.go:17]: Done, simplified to Cleanup(ctx, cleanAll bool) as you suggested. otelc go passes false, otelc cleanup passes true.
